sonar.projectKey=devops-cicd-security-platform
sonar.projectName=devops-cicd-security-platform
sonar.sources=src,scripts,configs,deployments,policies
sonar.exclusions=**/*.tar.gz,**/artifacts/**,**/reports/**,**/.git/**
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
